### ISSUE TITLE
DRC check fails due to report not existing

### ISSUE THREAD

**Issue by armleo** [efabless/mpw_precheck#123]
DRC check fails:

```
{{STEP UPDATE}} Executing Check 9 of 13: Klayout BEOL

Traceback (most recent call last):

  File "mpw_precheck.py", line 139, in <module>

    default_content='_default_content')

  File "mpw_precheck.py", line 100, in main

    run_precheck_sequence(precheck_config=precheck_config, project_config=project_config)

  File "mpw_precheck.py", line 68, in run_precheck_sequence

    results[check.__surname__] = check.run()

  File "/home/armleo/mpw_precheck/check_manager/__init__.py", line 130, in run

    self.klayout_cmd_extra_args)

  File "/home/armleo/mpw_precheck/checks/drc_checks/klayout/klayout_gds_drc_check.py", line 19, in klayout_gds_drc_check

    with open(report_file_path) as klayout_xml_report:

FileNotFoundError: [Errno 2] No such file or directory: '/home/armleo/Desktop/caravel_user_project_analog/precheck_results/18_MAR_2022___08_33_51/outputs/reports/klayout_beol_check.xml'
```

**Comment by DavidRLindley** [comment]
I'm closing this ticket due to age and staleness.  I have seen some cases of this due to multiple top level cells in the GDS file.  We are making changes to identify those conditions tracked elsewhere.
